---
services:
  device-grp-ui:
    ports:
      - "8080:8080"
    volumes:
      - "../:/app/"
    healthcheck:
      start_period: 180s
      timeout: 3s
      interval: 15s
      test: "curl -f http://device-grp-ui:8080/api/ || exit 1"

  device-grp-docs:
    entrypoint: "mkdocs serve -v -a 0.0.0.0:8001"
    ports:
      - "8001:8001"
    volumes:
      - "../:/app/"
    image: "device-grp-ui"
    container_name: "device-grp-docs"
    hostname: "device-grp-docs"
    healthcheck:
      disable: true
    tty: true

    depends_on:
      device-grp-ui:
        condition: "service_healthy"

volumes:
  app_data: {}
  doc_data: {}

