services:
  device-grp-redis:
    container_name: "device-grp-redis"
    hostname: "device-grp-redis"
    image: "redis:7-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    env_file:
      - "dev.env"
      - "creds.env"
    ports:
      - "6379:6379"