---
x-netbox-build: &netbox-build
    build:
      args:
        NETBOX_VER: "${NETBOX_VER}"
        PYTHON_VER: "${PYTHON_VER}"
        POETRY_VER: "${POETRY_VER}"
      context: ..
      dockerfile: "development/Dockerfile"

x-netbox-base: &netbox-base
  image: "device-grp-ui"
  container_name: "device-grp-ui"
  hostname: "device-grp-ui"
  env_file:
    - "dev.env"
    - "creds.env"
  tty: true


version: '3.8'
services:
  device-grp-ui:
    depends_on:
      device-grp-db:
        condition: "service_healthy"
      device-grp-redis:
        condition: "service_started"
    <<: [*netbox-build, *netbox-base]
