---
services:
  device-grp-ui:
    ports:
      - "8080:8080"
    volumes:
      - "../:/app/"

  device-grp-docs:
    entrypoint: "mkdocs serve -v -a 0.0.0.0:8001"
    ports:
      - "8001:8001"
    volumes:
      - "../:/app/"
    image: "device-grp-ui"
    container_name: "device-grp-docs"
    hostname: "device-grp-docs"
    healthcheck:
      disable: true
    tty: true

    depends_on:
      device-grp-ui:
        condition: "service_started"

volumes:
  app_data: {}
  doc_data: {}

