---
dev_addr: "127.0.0.1:8001"
site_name: "Physical Clusters - A Netbox Plugin - Documentation"
edit_uri: "blob/develop/docs/"
repo_name: "sapcc/netbox-physical-clusters"
repo_url: "https://github.com/sapcc/netbox-physical-clusters"
site_url: "https://pages.github.com/sapcc/netbox-physical-clusters"

nav:
  - Introduction: "index.md"
  - User Guide:
      - App Overview: "user/app_overview.md"
      - Using the App: "user/app_use_cases.md"
      - Getting Started: "user/app_getting_started.md"
  - Administrator Guide:
      - Install and Configure: "admin/install.md"
      - Upgrade: "admin/upgrade.md"
      - Uninstall: "admin/uninstall.md"
      - Release Notes:
        - "admin/release_notes/index.md"
        - v0.2: "admin/release_notes/version_0.2.md"
  - Developer Guide:
      - Design: "dev/design.md"
      - Extending the Plugin: "dev/extending.md"
      - Contributing to the Plugin: "dev/contributing.md"
      - Development Environment: "dev/dev_environment.md"



# ==================================================================================================================================
# Setting up the basic NAT docs theme
theme:
  icon:
    logo: fontawesome/solid/server
    # Change the above Icon to suit your project, if desired

# ==================================================================================================================================
#   Ignore and do not change anything below this line, these are the standard settings that should be in place for our documentation
# ==================================================================================================================================
# Setting up the basic NAT docs theme
    repo: fontawesome/brands/github
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.instant
    - toc.follow
    - toc.integrate
    - navigation.tracking

# ==================================================================================================================================
# Setting up the basic plugins
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: "python"
      handlers:
        python:
          paths: ["."]
          options:
            heading_level: 1
            show_root_heading: true
            show_root_members_full_path: true
# ==================================================================================================================================
# Setting up the required markdown extensions
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - abbr
  - attr_list
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
