# Generated by Django 4.2.11 on 2024-05-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_device_groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicegroup',
            old_name='cluster_type',
            new_name='device_group_type',
        ),
    ]
