# Generated by Django 4.2.5 on 2023-09-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0172_larger_power_draw_values'),
        ('ipam', '0066_iprange_mark_utilized'),
        ('netbox_physical_clusters', '0002_physicalcluster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalcluster',
            name='devices',
            field=models.ManyToManyField(to='dcim.device'),
        ),
        migrations.AddField(
            model_name='physicalcluster',
            name='primary_ip4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.ipaddress'),
        ),
    ]
